
// This file is auto generated by build/build-entry.js
import { VueConstructor } from 'vue/types';
import config from '../config/config';
const install=function(Vue:VueConstructor) {   
    const $config={value:config,writable: false }   

    Object.defineProperties(Vue, {
        $config,        
    }),
    Object.defineProperties(Vue.prototype, {
        $config
    })
}
export default{
    install
}